site_name: TK Debug Window

theme:
  name: material
  locale: en
  highlightjs: true

repo_url: https://github.com/jubnl/exam
repo_name: Exam Module 155
edit_uri: "blob/main/docs/"

site_author: "Julien Gunther"

plugins:
  - mkdocstrings
  - search

nav:
  - Home: index.md
  - "Debug Window Source": debug_window_source.md
  - "Log sender Source": log_sender_source.md
